SOUNDTOUCH_HTTP_PORT = 8090
SOUNDTOUCH_WEBSOCKET_PORT = 8080

HTTP_GET_TIMEOUT_SECONDS = 5
HTTP_POST_TIMEOUT_SECONDS = 3

DISCOVERY_SCAN_TIMEOUT_SECONDS = 5
DISCOVERY_REFRESH_TIMEOUT_SECONDS = 3
DISCOVERY_REFRESH_INTERVAL_SECONDS = 300

WEBSOCKET_CLOSE_RETRY_DELAY_SECONDS = 5
WEBSOCKET_LOOP_RETRY_DELAY_SECONDS = 10
WEBSOCKET_PING_INTERVAL_SECONDS = 30
WEBSOCKET_PING_TIMEOUT_SECONDS = 10

DEFAULT_VOLUME = 20
DEFAULT_PRESET = 1
DEFAULT_FADE_IN_DURATION_SECONDS = 300
DEFAULT_FADE_OUT_DURATION_SECONDS = 60
SPEAKER_BOOT_DELAY_SECONDS = 3
SOURCE_SETTLE_DELAY_SECONDS = 1
FADE_STATUS_RECHECK_STEP_INTERVAL = 5
SCHEDULER_LOOP_INTERVAL_SECONDS = 10